!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_fortran_module_num_threads (num_threadsf2pywra&
     &p)
      use fortran_module, only : num_threads
      integer num_threadsf2pywrap
      num_threadsf2pywrap = num_threads()
      end subroutine f2pywrap_fortran_module_num_threads
      
      subroutine f2pyinitfortran_module(f2pysetupfunc)
      use fortran_module, only : simulate_mutations
      use fortran_module, only : simulate_time_series
      use fortran_module, only : discrete_fit
      use fortran_module, only : discrete_fit_i
      interface 
      subroutine f2pywrap_fortran_module_num_threads (num_threadsf2pywra&
     &p, num_threads)
      integer num_threads
      integer num_threadsf2pywrap
      end subroutine f2pywrap_fortran_module_num_threads
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_fortran_module_num_threads,simulate_mu&
     &tations,simulate_time_series,discrete_fit,discrete_fit_i)
      end subroutine f2pyinitfortran_module


